### ISSUE TITLE
Mainnet run 1

### ISSUE THREAD

**Issue by prasannavl** [prasannavl/dfi-emissions-handler-bot#9]
- Run 1 errored on EVM publish. 
- Manual intervention needed, bot paused to ensure bug resolution, before unpausing. 

```
2024-01-25T14:20:25.469Z {
  evmJsonRpc: "http://localhost:8551",
  emissionsAddr: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea",
  evmAddr1: "0xD88Bb8359D694c974C9726b6201479a123212333",
  evmAddr1Share: 0.375,
  evmAddr2: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638",
  evmAddr2Share: 0.625,
  runIntervalMod: 1440,
  forceStart: true,
  startBlock: 3659200,
  endBlock: 1.7976931348623157e+308,
  maxDUSDPerBlock: 20,
  feeReserveAmount: 10
}
2024-01-25T14:20:25.471Z cli: /home/defi/defichain-4.0.5/bin/defi-cli
2024-01-25T14:20:25.473Z lastRunBlock: 0
2024-01-25T14:20:25.473Z create evm rpc provider for: http://localhost:8551
2024-01-25T14:20:25.473Z evm provider set
2024-01-25T14:20:25.473Z running block event loop
2024-01-25T14:20:25.492Z height BlockHeight { value: 3664805 }
2024-01-25T14:20:25.493Z runSequence: 3664805 5605
2024-01-25T14:20:25.660Z sequence chain start
{
  initHeight: BlockHeight { value: 3664805 },
  diffBlocks: 5605,
  emissionsAddr: Address { value: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea" },
  emissionsAddrErc55: Address { value: "0x63e460eE06ae1b5513B87460bA3a29197D6ABFA5" },
  evmAddr1: Address { value: "0xD88Bb8359D694c974C9726b6201479a123212333" },
  evmAddr2: Address { value: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638" },
  envOpts: {
    evmJsonRpc: "http://localhost:8551",
    emissionsAddr: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea",
    evmAddr1: "0xD88Bb8359D694c974C9726b6201479a123212333",
    evmAddr1Share: 0.375,
    evmAddr2: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638",
    evmAddr2Share: 0.625,
    runIntervalMod: 1440,
    forceStart: false,
    startBlock: 3659200,
    endBlock: 1.7976931348623157e+308,
    maxDUSDPerBlock: 20,
    feeReserveAmount: 10
  },
  balanceInitDfi: 1.98911853,
  balanceEvmInitDfi: 0n,
  balanceEvmInitDusd: 0n,
  balanceTokensInit: { DFI: 141438.85388616 },
  balanceTokensInitDfi: 141438.85388616,
  balanceTokensInitDusd: 0,
  poolPairInfoDusdDfi: {
    symbol: "DUSD-DFI",
    name: "Decentralized USD-Default Defi token",
    status: true,
    idTokenA: "15",
    idTokenB: "0",
    dexFeePctTokenA: 0.3,
    dexFeeInPctTokenA: 0.3,
    reserveA: 4354858.06536444,
    reserveB: 14251911.93615059,
    commission: 0.002,
    totalLiquidity: 7647301.22062465,
    "reserveA/reserveB": 0.30556307,
    "reserveB/reserveA": 3.27264671,
    tradeEnabled: true,
    ownerAddress: "8UAhRuUFCyFUHEPD7qvtj8Zy2HxF5HH5nb",
    blockCommissionA: 0,
    blockCommissionB: 0,
    rewardPct: 0,
    rewardLoanPct: 0.25,
    creationTx: "8334fa67b87332d658fc77b15ba09b8721c0a64f9a470441a449a784c7e97a68",
    creationHeight: 1367574,
    id: 17
  },
  dfiPriceForDusd: 3.27264671,
  dfiForDusdCappedPerBlock: 65.4529342,
  dfiToSwapPerBlock: 25.23440747299911,
  dfiToSwapForDiffBlocks: 141438.85388616,
  getEvmDusdContract: [Function: getEvmDusdContract],
  state: {
    currentHeight: BlockHeight { value: 3664805 },
    feeReserves: { balanceDfi: null },
    swapDfiToDusd: { swapHeight: null },
    postSwapCalc: {
      balanceTokens: null,
      balanceTokenDfi: null,
      balanceTokenDusd: null,
      dUsdToTransfer: null
    }
  }
}
2024-01-25T14:20:25.661Z refill utxo from account for: 10
wait for tx: 82deeb323a89061914e6ebf5984200cd047223b9f7ef2c5df4da79f411f763ea.
2024-01-25T14:21:11.008Z refill EVM DFI from account for: 10 with transferdomain (nonce: 0)
wait for tx: 3a9d3447e557444fac7172d0f0b7de02e9c6496d7b6367f0cfacfe196360edb2
2024-01-25T14:21:26.248Z swap: 141438.85388616 DFI to DUSD // 3664810
wait for tx: dcd29da3eb845cb54123cbba43fb8b3fb1ee875d759f4ca5bf19836d0329dd4c.
2024-01-25T14:22:11.397Z DUSD increase on address: 42708.81294559
2024-01-25T14:22:11.397Z burn: skip due to low reserves: 0
2024-01-25T14:22:11.411Z transfer domain: 42708.81294559 DUSD to EVM (nonce: 1)
wait for tx: 36b33f95240f4764526079400f32f9553d2c55645b42301f552dc8a4be64afd5.
2024-01-25T14:24:11.586Z evmAddr1Amount: 16015.804854596248 // 16015804854596249059328
2024-01-25T14:24:11.586Z evmAddr2Amount: 26693.00809099375 // 26693008090993749131264
2024-01-25T14:24:11.614Z approve DUSD to contract 1: 0xD88Bb8359D694c974C9726b6201479a123212333,16015804854596249059328
2024-01-25T14:24:11.614Z approve DUSD to contract 2: 0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638,26693008090993749131264
2024-01-25T14:24:11.614Z transfer DUSD to contract 1: 16015804854596249059328
2024-01-25T14:24:11.614Z transfer DUSD to contract 2: 26693008090993749131264
2024-01-25T14:24:54.809Z sequence chain failure
2024-01-25T14:24:54.809Z previous-ctx
{
  initHeight: { value: 3664805 },
  diffBlocks: 5605,
  emissionsAddr: { value: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea" },
  emissionsAddrErc55: { value: "0x63e460eE06ae1b5513B87460bA3a29197D6ABFA5" },
  evmAddr1: { value: "0xD88Bb8359D694c974C9726b6201479a123212333" },
  evmAddr2: { value: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638" },
  envOpts: {
    evmJsonRpc: "http://localhost:8551",
    emissionsAddr: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea",
    evmAddr1: "0xD88Bb8359D694c974C9726b6201479a123212333",
    evmAddr1Share: 0.375,
    evmAddr2: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638",
    evmAddr2Share: 0.625,
    runIntervalMod: 1440,
    forceStart: false,
    startBlock: 3659200,
    endBlock: 1.7976931348623157e+308,
    maxDUSDPerBlock: 20,
    feeReserveAmount: 10
  },
  balanceInitDfi: 1.98911853,
  balanceEvmInitDfi: "0",
  balanceEvmInitDusd: "0",
  balanceTokensInit: { DFI: 141438.85388616 },
  balanceTokensInitDfi: 141438.85388616,
  balanceTokensInitDusd: 0,
  poolPairInfoDusdDfi: {
    symbol: "DUSD-DFI",
    name: "Decentralized USD-Default Defi token",
    status: true,
    idTokenA: "15",
    idTokenB: "0",
    dexFeePctTokenA: 0.3,
    dexFeeInPctTokenA: 0.3,
    reserveA: 4354858.06536444,
    reserveB: 14251911.93615059,
    commission: 0.002,
    totalLiquidity: 7647301.22062465,
    "reserveA/reserveB": 0.30556307,
    "reserveB/reserveA": 3.27264671,
    tradeEnabled: true,
    ownerAddress: "8UAhRuUFCyFUHEPD7qvtj8Zy2HxF5HH5nb",
    blockCommissionA: 0,
    blockCommissionB: 0,
    rewardPct: 0,
    rewardLoanPct: 0.25,
    creationTx: "8334fa67b87332d658fc77b15ba09b8721c0a64f9a470441a449a784c7e97a68",
    creationHeight: 1367574,
    id: 17
  },
  dfiPriceForDusd: 3.27264671,
  dfiForDusdCappedPerBlock: 65.4529342,
  dfiToSwapPerBlock: 25.23440747299911,
  dfiToSwapForDiffBlocks: 141438.85388616,
  state: {
    currentHeight: { value: 3664815 },
    feeReserves: { balanceDfi: 11.98910202 },
    swapDfiToDusd: { swapHeight: { value: 3664811 } },
    postSwapCalc: {
      balanceTokens: { DFI: 83.90864932, DUSD: 42708.81294559 },
      balanceTokenDfi: 83.90864932,
      balanceTokenDusd: 42708.81294559,
      dUsdToTransfer: 42708.81294559
    }
  }
}
2024-01-25T14:24:54.810Z current-ctx
{
  initHeight: BlockHeight { value: 3664805 },
  diffBlocks: 5605,
  emissionsAddr: Address { value: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea" },
  emissionsAddrErc55: Address { value: "0x63e460eE06ae1b5513B87460bA3a29197D6ABFA5" },
  evmAddr1: Address { value: "0xD88Bb8359D694c974C9726b6201479a123212333" },
  evmAddr2: Address { value: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638" },
  envOpts: {
    evmJsonRpc: "http://localhost:8551",
    emissionsAddr: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea",
    evmAddr1: "0xD88Bb8359D694c974C9726b6201479a123212333",
    evmAddr1Share: 0.375,
    evmAddr2: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638",
    evmAddr2Share: 0.625,
    runIntervalMod: 1440,
    forceStart: false,
    startBlock: 3659200,
    endBlock: 1.7976931348623157e+308,
    maxDUSDPerBlock: 20,
    feeReserveAmount: 10
  },
  balanceInitDfi: 1.98911853,
  balanceEvmInitDfi: 0n,
  balanceEvmInitDusd: 0n,
  balanceTokensInit: { DFI: 141438.85388616 },
  balanceTokensInitDfi: 141438.85388616,
  balanceTokensInitDusd: 0,
  poolPairInfoDusdDfi: {
    symbol: "DUSD-DFI",
    name: "Decentralized USD-Default Defi token",
    status: true,
    idTokenA: "15",
    idTokenB: "0",
    dexFeePctTokenA: 0.3,
    dexFeeInPctTokenA: 0.3,
    reserveA: 4354858.06536444,
    reserveB: 14251911.93615059,
    commission: 0.002,
    totalLiquidity: 7647301.22062465,
    "reserveA/reserveB": 0.30556307,
    "reserveB/reserveA": 3.27264671,
    tradeEnabled: true,
    ownerAddress: "8UAhRuUFCyFUHEPD7qvtj8Zy2HxF5HH5nb",
    blockCommissionA: 0,
    blockCommissionB: 0,
    rewardPct: 0,
    rewardLoanPct: 0.25,
    creationTx: "8334fa67b87332d658fc77b15ba09b8721c0a64f9a470441a449a784c7e97a68",
    creationHeight: 1367574,
    id: 17
  },
  dfiPriceForDusd: 3.27264671,
  dfiForDusdCappedPerBlock: 65.4529342,
  dfiToSwapPerBlock: 25.23440747299911,
  dfiToSwapForDiffBlocks: 141438.85388616,
  getEvmDusdContract: [Function: getEvmDusdContract],
  state: {
    currentHeight: BlockHeight { value: 3664815 },
    feeReserves: { balanceDfi: 11.98910202 },
    swapDfiToDusd: { swapHeight: BlockHeight { value: 3664811 } },
    postSwapCalc: {
      balanceTokens: { DFI: 83.90864932, DUSD: 42708.81294559 },
      balanceTokenDfi: 83.90864932,
      balanceTokenDusd: 42708.81294559,
      dUsdToTransfer: 42708.81294559
    }
  }
}
Error: could not coalesce error (error={ "code": -32001, "message": "Custom error: Could not publish raw transaction: 02f88e82046a03808502ad741300830186a094c5b7aac761aa3c3f34a3ceb1333f6431d811d63880a4beceed390000000000000000000000000000000000000000000005
a707e6f92406400000c080a0f19d2f8cbe31bbb810b6b6467d17c28bb91f4e7848f99469a1461a19cd38ff1ea04bc18de778da39ab6261096a61d51003cf956ed0f41da8e7ac30e2433ac38ace reason: evm-low-fee (code 16)" }, payload={ "id": 17, "jsonrpc": "2.0", "method": "eth_sendTransact
ion", "params": [ { "data": "0xbeceed390000000000000000000000000000000000000000000005a707e6f92406400000", "from": "0x63e460ee06ae1b5513b87460ba3a29197d6abfa5", "gas": "0x186a0", "to": "0xc5b7aac761aa3c3f34a3ceb1333f6431d811d638" } ] }, code=UNKNOWN_ERROR
, version=6.10.0)
    at nt (https://esm.sh/v135/ethers@6.10.0/denonext/utils.js:2:1724)
    at b.getRpcError (https://esm.sh/v135/ethers@6.10.0/denonext/providers.js:3:64282)
    at https://esm.sh/v135/ethers@6.10.0/denonext/providers.js:3:57880
    at eventLoopTick (ext:core/01_core.js:59:7) {
  code: "UNKNOWN_ERROR",
  error: {
    code: -32001,
    message: "Custom error: Could not publish raw transaction: 02f88e82046a03808502ad741300830186a094c5b7aac761aa3"... 269 more characters
  },
  payload: {
    method: "eth_sendTransaction",
    params: [
      {
        gas: "0x186a0",
        from: "0x63e460ee06ae1b5513b87460ba3a29197d6abfa5",
        to: "0xc5b7aac761aa3c3f34a3ceb1333f6431d811d638",
        data: "0xbeceed390000000000000000000000000000000000000000000005a707e6f92406400000"
      }
    ],
    id: 17,
    jsonrpc: "2.0"
  },
  shortMessage: "could not coalesce error"
}
2024-01-25T14:24:54.819Z height BlockHeight { value: 3664820 }
2024-01-25T14:24:54.819Z runSequence: 3664820 5620
2024-01-25T14:24:54.828Z approve DUSD to contract 1: wait for 0xfd3777fa337e8daf13b8b08765c903dc712242a9993156d4e1369316148ffce6
2024-01-25T14:24:54.856Z approve DUSD to contract 1: done
2024-01-25T14:24:54.956Z sequence chain start
{
  initHeight: BlockHeight { value: 3664820 },
  diffBlocks: 5620,
  emissionsAddr: Address { value: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea" },
  emissionsAddrErc55: Address { value: "0x63e460eE06ae1b5513B87460bA3a29197D6ABFA5" },
  evmAddr1: Address { value: "0xD88Bb8359D694c974C9726b6201479a123212333" },
  evmAddr2: Address { value: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638" },
  envOpts: {
    evmJsonRpc: "http://localhost:8551",
    emissionsAddr: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea",
    evmAddr1: "0xD88Bb8359D694c974C9726b6201479a123212333",
    evmAddr1Share: 0.375,
    evmAddr2: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638",
    evmAddr2Share: 0.625,
    runIntervalMod: 1440,
    forceStart: false,
    startBlock: 3659200,
    endBlock: 1.7976931348623157e+308,
    maxDUSDPerBlock: 20,
    feeReserveAmount: 10
  },
  balanceInitDfi: 11.98908834,
  balanceEvmInitDfi: 9999489020000000000n,
  balanceEvmInitDusd: 42708812945590000000000n,
  balanceTokensInit: { DFI: 153.1810822 },
  balanceTokensInitDfi: 153.1810822,
  balanceTokensInitDusd: 0,
  poolPairInfoDusdDfi: {
    symbol: "DUSD-DFI",
    name: "Decentralized USD-Default Defi token",
    status: true,
    idTokenA: "15",
    idTokenB: "0",
    dexFeePctTokenA: 0.3,
    dexFeeInPctTokenA: 0.3,
    reserveA: 4312137.16333057,
    reserveB: 14393107.47575387,
    commission: 0.002,
    totalLiquidity: 7647301.22062465,
    "reserveA/reserveB": 0.29959737,
    "reserveB/reserveA": 3.33781299,
    tradeEnabled: true,
    ownerAddress: "8UAhRuUFCyFUHEPD7qvtj8Zy2HxF5HH5nb",
    blockCommissionA: 0,
    blockCommissionB: 0,
    rewardPct: 0,
    rewardLoanPct: 0.25,
    creationTx: "8334fa67b87332d658fc77b15ba09b8721c0a64f9a470441a449a784c7e97a68",
    creationHeight: 1367574,
    id: 17
  },
  dfiPriceForDusd: 3.33781299,
  dfiForDusdCappedPerBlock: 66.75625980000001,
  dfiToSwapPerBlock: 0.027256420320284695,
  dfiToSwapForDiffBlocks: 153.1810822,
  getEvmDusdContract: [Function: getEvmDusdContract],
  state: {
    currentHeight: BlockHeight { value: 3664820 },
    feeReserves: { balanceDfi: null },
    swapDfiToDusd: { swapHeight: null },
    postSwapCalc: {
      balanceTokens: null,
      balanceTokenDfi: null,
      balanceTokenDusd: null,
      dUsdToTransfer: null
    }
  }
}
2024-01-25T14:24:54.957Z swap: 153.1810822 DFI to DUSD // 3664820
wait for tx: 0b728b23cd0de40bd707ac8bc03e9e045ebb311a73732816a0f50e1a28a95873.^C
```

**Comment by Krysh90** [comment]
Approve TX for the missing AddReward to 2Y Bond contract:
https://mainnet-dmc.mydefichain.com:8441/tx/0xe42d5075825aff0f0a8220bd601e5871e999036386b2e09917704e3707e0de11

contract address: `0xc5b7aac761aa3c3f34a3ceb1333f6431d811d638`
amount: `26693008090993749131264`

values are matching log entries of `2024-01-25T14:24:11.586Z` and further.

Please someone else verifies and double-checks provided info.

**Comment by prasannavl** [comment]
Issue: Seems ethers library's populateTransaction never set the nonce value according to the params from the log messages. Need to dig into why, but this is a separate issue. This in turn resulted in an unexpected scenario on nonce calculation for parallel TXs. 

Bot workaround: Remove parallel TXs entirely just to be safe and also use `GetTransactionCount` manually to safeguard against this. 

Next steps: 
- Re-broadcast the above EVM TX manually. 
- Reverse the final step of `0b728b23cd0de40bd707ac8bc03e9e045ebb311a73732816a0f50e1a28a95873`
  - 2024-01-25T14:24:54.957Z swap: 153.1810822 DFI to DUSD // 3664820
  - Reversal of the swap is better, since otherwise, we need to recreate the exact state for the bot to continue from here, or manually craft exact precise number, both of which are error prone. Revert is the safest solution to get it to clean slate. This also minimises the manual intervention, as it's ideal to have the least manual intervention possible. 
 - Start the bot again with updated start block, so that lastRunState is updated to the previous run.

**Comment by prasannavl** [comment]
Results: 

1. Rebroadcast Transaction: `0x67dea2accb99b2752679dc62dee5794740a3fc1f7e35baa9be5a414b5068ac4d` 
2. Poolswap reversal: `0914e05779ad10167bfff0683f2a224b924c6194c0a4196f8891d493c7c6d28e`

**Comment by prasannavl** [comment]
Starting bot with, for a manual run, since the lastRun wouldn't be saved.  

```
ENV=mainnet BOT_START_BLOCK=3664805 BOT_FORCE_START=1 ./emissions-handler-bot
```

**Comment by prasannavl** [comment]
Result:

```
2024-01-25T18:04:14.565Z {
  evmJsonRpc: "http://localhost:8551",
  emissionsAddr: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea",
  evmAddr1: "0xD88Bb8359D694c974C9726b6201479a123212333",
  evmAddr1Share: 0.375,
  evmAddr2: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638",
  evmAddr2Share: 0.625,
  runIntervalMod: 1440,
  forceStart: true,
  startBlock: 3664805,
  endBlock: 1.7976931348623157e+308,
  maxDUSDPerBlock: 20,
  feeReserveAmount: 10
}
2024-01-25T18:04:14.567Z cli: defi-cli
2024-01-25T18:04:14.569Z lastRunBlock: 0
2024-01-25T18:04:14.569Z create evm rpc provider for: http://localhost:8551
2024-01-25T18:04:14.569Z evm provider set
2024-01-25T18:04:14.569Z running block event loop
2024-01-25T18:04:14.596Z height BlockHeight { value: 3665243 }
2024-01-25T18:04:14.596Z runSequence: 3665243 438
2024-01-25T18:04:14.761Z sequence chain start
{
  initHeight: BlockHeight { value: 3665243 },
  diffBlocks: 438,
  emissionsAddr: Address { value: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea" },
  emissionsAddrErc55: Address { value: "0x63e460eE06ae1b5513B87460bA3a29197D6ABFA5" },
  evmAddr1: Address { value: "0xD88Bb8359D694c974C9726b6201479a123212333" },
  evmAddr2: Address { value: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638" },
  envOpts: {
    evmJsonRpc: "http://localhost:8551",
    emissionsAddr: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea",
    evmAddr1: "0xD88Bb8359D694c974C9726b6201479a123212333",
    evmAddr1Share: 0.375,
    evmAddr2: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638",
    evmAddr2Share: 0.625,
    runIntervalMod: 1440,
    forceStart: false,
    startBlock: 3664805,
    endBlock: 1.7976931348623157e+308,
    maxDUSDPerBlock: 20,
    feeReserveAmount: 10
  },
  balanceInitDfi: 11.98908274,
  balanceEvmInitDfi: 9997527200000000000n,
  balanceEvmInitDusd: 1809408n,
  balanceTokensInit: { DFI: 4989.89732771 },
  balanceTokensInitDfi: 4989.89732771,
  balanceTokensInitDusd: 0,
  poolPairInfoDusdDfi: {
    symbol: "DUSD-DFI",
    name: "Decentralized USD-Default Defi token",
    status: true,
    idTokenA: "15",
    idTokenB: "0",
    dexFeePctTokenA: 0.3,
    dexFeeInPctTokenA: 0.3,
    reserveA: 4325503.41395359,
    reserveB: 14349007.05631451,
    commission: 0.002,
    totalLiquidity: 7647401.2728059,
    "reserveA/reserveB": 0.30144966,
    "reserveB/reserveA": 3.31730337,
    tradeEnabled: true,
    ownerAddress: "8UAhRuUFCyFUHEPD7qvtj8Zy2HxF5HH5nb",
    blockCommissionA: 0,
    blockCommissionB: 0,
    rewardPct: 0,
    rewardLoanPct: 0.25,
    creationTx: "8334fa67b87332d658fc77b15ba09b8721c0a64f9a470441a449a784c7e97a68",
    creationHeight: 1367574,
    id: 17
  },
  dfiPriceForDusd: 3.31730337,
  dfiForDusdCappedPerBlock: 66.3460674,
  dfiToSwapPerBlock: 11.392459652305936,
  dfiToSwapForDiffBlocks: 4989.89732771,
  getEvmDusdContract: [Function: getEvmDusdContract],
  state: {
    currentHeight: BlockHeight { value: 3665243 },
    feeReserves: { balanceDfi: null },
    swapDfiToDusd: { swapHeight: null },
    postSwapCalc: {
      balanceTokens: null,
      balanceTokenDfi: null,
      balanceTokenDusd: null,
      dUsdToTransfer: null
    }
  }
}
2024-01-25T18:04:14.762Z swap: 4989.89732771 DFI to DUSD // 3665243
wait for tx: d6b32d67e86062b929f1cd5a6f2591f658393575e9feb4530ecc5800728330f8.
2024-01-25T18:05:45.024Z DUSD increase on address: 1500.67366855
2024-01-25T18:05:45.024Z burn: skip due to low reserves: 0
2024-01-25T18:05:45.039Z transfer domain: 1500.67366855 DUSD to EVM (nonce: 6)
wait for tx: 73a99b0ddc6267e4c66f4c2e0590c2ade6c0841bb15f28e8ac4650f1fa78fd8e.
2024-01-25T18:08:30.394Z evmAddr1Amount: 562.75262570625 // 562752625706250010624
2024-01-25T18:08:30.394Z evmAddr2Amount: 937.92104284375 // 937921042843749974016
2024-01-25T18:08:30.410Z approve DUSD to contract 1: 0xD88Bb8359D694c974C9726b6201479a123212333,5627526257062500106
24
2024-01-25T18:09:09.011Z approve DUSD to contract 2: 0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638,9379210428437499740
16
2024-01-25T18:12:16.178Z transfer DUSD to contract 1: 562752625706250010624
2024-01-25T18:18:24.042Z transfer DUSD to contract 2: 937921042843749974016
{
  initHeight: BlockHeight { value: 3665243 },
  diffBlocks: 438,
  emissionsAddr: Address { value: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea" },
  emissionsAddrErc55: Address { value: "0x63e460eE06ae1b5513B87460bA3a29197D6ABFA5" },
  evmAddr1: Address { value: "0xD88Bb8359D694c974C9726b6201479a123212333" },
  evmAddr2: Address { value: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638" },
  envOpts: {
    evmJsonRpc: "http://localhost:8551",
    emissionsAddr: "df1qlwvtdrh4a4zln3k56rqnx8chu8t0sqx36syaea",
    evmAddr1: "0xD88Bb8359D694c974C9726b6201479a123212333",
    evmAddr1Share: 0.375,
    evmAddr2: "0xc5B7aAc761aa3C3f34A3cEB1333f6431d811d638",
    evmAddr2Share: 0.625,
    runIntervalMod: 1440,
    forceStart: false,
    startBlock: 3664805,
    endBlock: 1.7976931348623157e+308,
    maxDUSDPerBlock: 20,
    feeReserveAmount: 10
  },
  balanceInitDfi: 11.98908274,
  balanceEvmInitDfi: 9997527200000000000n,
  balanceEvmInitDusd: 1809408n,
  balanceTokensInit: { DFI: 4989.89732771 },
  balanceTokensInitDfi: 4989.89732771,
  balanceTokensInitDusd: 0,
  poolPairInfoDusdDfi: {
    symbol: "DUSD-DFI",
    name: "Decentralized USD-Default Defi token",
    status: true,
    idTokenA: "15",
    idTokenB: "0",
    dexFeePctTokenA: 0.3,
    dexFeeInPctTokenA: 0.3,
    reserveA: 4325503.41395359,
    reserveB: 14349007.05631451,
    commission: 0.002,
    totalLiquidity: 7647401.2728059,
    "reserveA/reserveB": 0.30144966,
    "reserveB/reserveA": 3.31730337,
    tradeEnabled: true,
    ownerAddress: "8UAhRuUFCyFUHEPD7qvtj8Zy2HxF5HH5nb",
    blockCommissionA: 0,
    blockCommissionB: 0,
    rewardPct: 0,
    rewardLoanPct: 0.25,
    creationTx: "8334fa67b87332d658fc77b15ba09b8721c0a64f9a470441a449a784c7e97a68",
    creationHeight: 1367574,
    id: 17
  },
  dfiPriceForDusd: 3.31730337,
  dfiForDusdCappedPerBlock: 66.3460674,
  dfiToSwapPerBlock: 11.392459652305936,
  dfiToSwapForDiffBlocks: 4989.89732771,
  getEvmDusdContract: [Function: getEvmDusdContract],
  state: {
    currentHeight: BlockHeight { value: 3665249 },
    feeReserves: { balanceDfi: null },
    swapDfiToDusd: { swapHeight: BlockHeight { value: 3665244 } },
    postSwapCalc: {
      balanceTokens: { DFI: 57.7270274, DUSD: 1500.67366855 },
      balanceTokenDfi: 57.7270274,
      balanceTokenDusd: 1500.67366855,
      dUsdToTransfer: 1500.67366855
    }
  }
}
2024-01-25T18:19:42.897Z sequence chain completed
2024-01-25T18:19:42.925Z height BlockHeight { value: 3665274 }
```

**Comment by prasannavl** [comment]
Bot restart with usual deployment parameters without env overrides.

**Comment by htsplex** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
qzhha, @therealt3nzin, @ruankranz, @phamducminh, @NPann, @atavism, @jbonsant, @HeHuiqi, @ng1091, @McRonnie23, @tvpeter, @mikeandersun, @fed-franz, @MOZGIII, @notsheesh, @AbheetChaudhary, @moclouds, @dily3825002, @gnovelli, @mg0314a, @CvGreen, @Stillam, @Omni-Engineering, @FishManHome, @fujiwaraizuho, @ParaXY, @itll, @nighthawk469, @fengya90, @oguzzkilic, @kimiko88, @sharkanet, @emilpaw, @Fahimsarkarisrafil, @suman-somu, @marko-kukovec, @fuhehua, @shichen35, @tonomoshia, @cbouvier15, @GodfreyJohnson, @shangyazhou, @Spacebody, @bsprenger, @nn1900, @wfqdreamcity, @voidnerd, @reymont, @rogue-wild, @MickHerbivore
